//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pupa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pupa.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dadwdwd9894.
        /// </summary>
        internal static string AESIVKey {
            get {
                return ResourceManager.GetString("AESIVKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dadwadawdwd9894.
        /// </summary>
        internal static string AESSecretKey {
            get {
                return ResourceManager.GetString("AESSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waruna.
        /// </summary>
        internal static string DatabaseConnectionName {
            get {
                return ResourceManager.GetString("DatabaseConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.waruna-group.co.id.
        /// </summary>
        internal static string FtpHost {
            get {
                return ResourceManager.GetString("FtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KekuatanHalilint4r.
        /// </summary>
        internal static string FtpPassword {
            get {
                return ResourceManager.GetString("FtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string FtpPort {
            get {
                return ResourceManager.GetString("FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heris.
        /// </summary>
        internal static string FtpUser {
            get {
                return ResourceManager.GetString("FtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hastalavista2021DD.
        /// </summary>
        internal static string JWTIssuer {
            get {
                return ResourceManager.GetString("JWTIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lpjqtjsfcmxqtbceahqzotigxngfyzuvsjcujwsibwkkuiftluxvsmesgvoeiqhystbvbkqdydxdgahqzadyribobbcocxnvivjjjqfapsmvhjnygxaednafmxlhadiw.
        /// </summary>
        internal static string JWTSecret {
            get {
                return ResourceManager.GetString("JWTSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /home/ict/uploads.
        /// </summary>
        internal static string OverseaAttachmentPath {
            get {
                return ResourceManager.GetString("OverseaAttachmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /home/ict/uploads.
        /// </summary>
        internal static string PublicStaticPath {
            get {
                return ResourceManager.GetString("PublicStaticPath", resourceCulture);
            }
        }
    }
}
