-- ============================================================================
-- Dynamic Requisition Form (wizard) — 3 tabel baru: Template -> Config -> Data.
--
-- Referensi desain: Pupa/docs/dynamic-requisition-wizard-recommended.md
--
-- ADITIF & AMAN UNTUK PRODUCTION:
--   - Hanya CREATE TABLE baru. Tidak menyentuh Requisition / RequisitionDetail
--     atau tabel lain yang sudah ada.
--   - Tidak ada backfill, tidak ada dual-write, tidak ada DROP COLUMN.
--   - Requisition lama tetap berjalan apa adanya.
--
-- PostgreSQL. Schema dikelola manual (tanpa EF migrations). Jalankan sekali
-- terhadap database Beesuite (staging dulu, verifikasi, baru production).
-- Semua langkah idempoten (aman dijalankan ulang).
--
-- DEPLOY ORDER: jalankan file ini LEBIH DULU, baru deploy PupaAPI.
-- ============================================================================

BEGIN;

-- ── 1. TEMPLATE — blueprint wizard reusable (versioned) ──────────────────────
CREATE TABLE IF NOT EXISTS "RequisitionFormTemplate" (
    "ID"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"        varchar(100) NOT NULL,
    "Name"        varchar(255) NOT NULL,
    "Version"     integer      NOT NULL DEFAULT 1,
    "SchemaJson"  jsonb        NOT NULL DEFAULT '{}'::jsonb,
    "IsActive"    boolean      NOT NULL DEFAULT true,
    "IsPublished" boolean      NOT NULL DEFAULT false,
    "CreatedAt"   timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAt"   timestamptz  NOT NULL DEFAULT now(),
    "CreatedBy"   varchar(100) NULL
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_reqformtpl_code_ver') THEN
        ALTER TABLE "RequisitionFormTemplate"
            ADD CONSTRAINT "uq_reqformtpl_code_ver" UNIQUE ("Code", "Version");
    END IF;
END $$;

-- ── 2. CONFIG — per ItemCode (pakai template ATAU schema sendiri) ────────────
CREATE TABLE IF NOT EXISTS "RequisitionFormConfig" (
    "ID"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode"    varchar(100) NOT NULL,
    "EntityType"  varchar(30)  NOT NULL DEFAULT 'RequisitionDetail',  -- Requisition | RequisitionDetail
    "Mode"        varchar(20)  NOT NULL,                              -- Template | Custom
    "TemplateID"  integer      NULL REFERENCES "RequisitionFormTemplate"("ID") ON DELETE SET NULL,
    "SchemaJson"  jsonb        NULL,
    "IsActive"    boolean      NOT NULL DEFAULT true,
    "CreatedAt"   timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAt"   timestamptz  NOT NULL DEFAULT now(),
    "CreatedBy"   varchar(100) NULL,
    CONSTRAINT "ck_reqformcfg_mode" CHECK (
        ("Mode" = 'Template' AND "TemplateID" IS NOT NULL)
     OR ("Mode" = 'Custom'   AND "SchemaJson" IS NOT NULL)
    )
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_reqformcfg_item_entity') THEN
        ALTER TABLE "RequisitionFormConfig"
            ADD CONSTRAINT "uq_reqformcfg_item_entity" UNIQUE ("ItemCode", "EntityType");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_reqformcfg_item"
    ON "RequisitionFormConfig" ("ItemCode", "EntityType", "IsActive");

-- ── 3. DATA — jawaban per requisition + snapshot config mentah ───────────────
CREATE TABLE IF NOT EXISTS "RequisitionFormData" (
    "ID"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RequisitionID"       integer      NOT NULL
        REFERENCES "Requisition"("ID") ON DELETE CASCADE,
    "RequisitionDetailID" integer      NULL
        REFERENCES "RequisitionDetail"("ID") ON DELETE CASCADE,
    "ItemCode"            varchar(100) NULL,
    "ConfigID"            integer      NULL
        REFERENCES "RequisitionFormConfig"("ID") ON DELETE SET NULL,
    "TemplateID"          integer      NULL
        REFERENCES "RequisitionFormTemplate"("ID") ON DELETE SET NULL,
    "SchemaSnapshot"      jsonb        NOT NULL,
    "Values"              jsonb        NOT NULL DEFAULT '{}'::jsonb,
    "Status"              varchar(20)  NOT NULL DEFAULT 'Draft',
    "CreatedAt"           timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAt"           timestamptz  NOT NULL DEFAULT now(),
    "CreatedBy"           varchar(100) NULL,
    "UpdatedBy"           varchar(100) NULL,
    CONSTRAINT "ck_reqformdata_entity" CHECK (
        "RequisitionDetailID" IS NULL OR "RequisitionID" IS NOT NULL
    )
);

-- Satu form header per Requisition (RequisitionDetailID IS NULL) ...
CREATE UNIQUE INDEX IF NOT EXISTS "uq_reqformdata_header"
    ON "RequisitionFormData" ("RequisitionID")
    WHERE "RequisitionDetailID" IS NULL;
-- ... dan satu form per RequisitionDetail.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_reqformdata_detail"
    ON "RequisitionFormData" ("RequisitionDetailID")
    WHERE "RequisitionDetailID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_reqformdata_requisition" ON "RequisitionFormData" ("RequisitionID");
CREATE INDEX IF NOT EXISTS "idx_reqformdata_item"        ON "RequisitionFormData" ("ItemCode");

COMMIT;

-- ── Verifikasi (jalankan manual setelah COMMIT) ─────────────────────────────
-- SELECT table_name FROM information_schema.tables
--  WHERE table_name IN ('RequisitionFormTemplate','RequisitionFormConfig','RequisitionFormData');
