-- BeeSuite Menu Management: reuse the existing Menu / LaunchPointTemplate /
-- LaunchPoint tables (already used by a different, unrelated frontend on
-- this same database — 49 existing Menu rows, /purchasing, /logistic, etc
-- routes). BeeSuite's own rows are added ALONGSIDE those, never touching
-- them, using the "BS_" MenuCode / "BS_ROLE_" TemplateName prefix so every
-- BeeSuite query can filter to just its own rows.
--
-- Run against both beesuite (prod) and beesuite_staging via psql, same
-- workflow used all session.

BEGIN;

-- 1) New columns -------------------------------------------------------
ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "IsComingSoon" boolean NOT NULL DEFAULT false;
ALTER TABLE "LaunchPointTemplate" ADD COLUMN IF NOT EXISTS "IsComingSoon" boolean NULL;
ALTER TABLE "LaunchPoint" ADD COLUMN IF NOT EXISTS "IsComingSoon" boolean NULL;

-- 2) BeeSuite menu catalog ----------------------------------------------
-- MenuCode, MenuName, Category, Route, SortOrder
INSERT INTO "Menu" ("MenuCode","MenuName","Category","Route","SortOrder","IsActive")
SELECT v.code, v.name, v.category, v.route, v.sort, true
FROM (VALUES
  ('BS_ITEM_REQUEST','Item Request','REQUESTS','/item-request',1),
  ('BS_QUICK_ORDER','Quick Order','REQUESTS','/quick-order',2),
  ('BS_USAGE','Usage','REQUESTS','/usage',3),
  ('BS_JOB_REQUEST','Job Request','REQUESTS','/job-request',4),
  ('BS_BUNKER_REQUEST','Bunker Request','REQUESTS','/bunker-request',5),
  ('BS_SHIPMENT_REQUEST','Shipment Request','REQUESTS','/shipment-request',6),
  ('BS_TRACK_ITEM','Track Item','OTHERS','/track-item',1),
  ('BS_FEEDBACK','Feedback','OTHERS','/feedback',2),
  ('BS_PART_BOOK','Part Book','RESOURCES','/part-book',1),
  ('BS_APPROVALS','Approvals','APPROVALS','/approvals',1),
  ('BS_USER_MANAGEMENT','User Management','MANAGEMENT','/users',1),
  ('BS_APPROVAL_RULES','Approval Rules','MANAGEMENT','/approval-rules',2),
  ('BS_APPROVAL_RULES_V2','Approval Rules v2','MANAGEMENT','/approval-rules-v2',3),
  ('BS_DELEGATE_APPROVER','Delegate Approver','MANAGEMENT','/delegate-approver',4),
  ('BS_RESEND_APPROVAL','Resend Approval','MANAGEMENT','/resend-approval',5),
  ('BS_DOCUMENT_NUMBERING','Document Numbering','MANAGEMENT','/document-numbering',6),
  ('BS_VESSEL_MANAGEMENT','Vessel Management','MANAGEMENT','/vessels',7),
  ('BS_COA_MANAGEMENT','COA Management','MANAGEMENT','/categories',8),
  ('BS_STOCK_CATEGORY','Stock Category','MANAGEMENT','/stock-category',9),
  ('BS_ITEM_MANAGEMENT','Item Management','MANAGEMENT','/item-management',10),
  ('BS_QUICK_ORDER_ITEMS','Quick Order Items','MANAGEMENT','/quick-order-items',11),
  ('BS_JOB_REQUEST_ITEM','Job Request Item','MANAGEMENT','/job-request-item',12),
  ('BS_MEDIA','Media','MANAGEMENT','/media',13),
  ('BS_MENU_MANAGEMENT','Menu Management','MANAGEMENT','/menu-management',14),
  ('BS_WHATSAPP_DEVICE','Whatsapp Device','SYSTEM','/whatsapp-device',1),
  ('BS_SYSTEM_LOGS','System Logs','SYSTEM','/system-logs',2),
  ('BS_CACHE_CONTROL','Cache Control','SYSTEM','/cache-control',3),
  ('BS_REQUISITION_ADMIN','Requisition Admin','SYSTEM','/requisition-admin',4),
  ('BS_JOB_REQUEST_ADMIN','Job Request Admin','SYSTEM','/job-request-admin',5),
  ('BS_JOB_REQUEST_PRUNE','Job Request Prune','SYSTEM','/job-request-prune',6),
  ('BS_SETTINGS','Settings','SYSTEM','/settings',7),
  ('BS_REPAIR_JOB_REQUEST','Repair Job Request','REPAIR','/repair-job-request',1),
  ('BS_OUTSTANDING_SERVICE_ATTENDANCE','Outstanding Service Attendance','REPAIR',null,2),
  ('BS_REPAIR_SERVICE_ORDERS','Repair Service Orders','REPAIR','/repair-service-orders',3),
  ('BS_MOBILIZATION','Mobilization','REPAIR','/arrangement-monitor',4),
  ('BS_ATTENDANCE_TRIP','Attendance Trip','REPAIR','/attendance-trip',5),
  ('BS_TECHNICIAN_CALENDAR','Technician Calendar','REPAIR',null,6),
  ('BS_SERVICE_REPORT','Service Report','REPAIR','/service-report?scope=all',7),
  ('BS_SERVICE_HISTORY','Service History','REPAIR',null,8),
  ('BS_MY_SERVICE_REPORT','My Service Report','REPAIR','/my-service-report',9)
) AS v(code, name, category, route, sort)
WHERE NOT EXISTS (SELECT 1 FROM "Menu" m WHERE m."MenuCode" = v.code);

-- 3) Per-role default templates ------------------------------------------
-- (TemplateName, MenuCode, SortOrder, IsComingSoon override or NULL=inherit)
INSERT INTO "LaunchPointTemplate" ("TemplateName","MenuID","Name","SortOrder","IsActive","IsComingSoon")
SELECT v.tmpl, m."ID", m."MenuName", v.sort, true, v.soon
FROM (VALUES
  -- SYSADMIN
  ('BS_ROLE_SYSADMIN','BS_USER_MANAGEMENT',1,NULL::boolean),
  ('BS_ROLE_SYSADMIN','BS_APPROVAL_RULES',2,NULL),
  ('BS_ROLE_SYSADMIN','BS_APPROVAL_RULES_V2',3,NULL),
  ('BS_ROLE_SYSADMIN','BS_DELEGATE_APPROVER',4,NULL),
  ('BS_ROLE_SYSADMIN','BS_RESEND_APPROVAL',5,NULL),
  ('BS_ROLE_SYSADMIN','BS_DOCUMENT_NUMBERING',6,NULL),
  ('BS_ROLE_SYSADMIN','BS_VESSEL_MANAGEMENT',7,NULL),
  ('BS_ROLE_SYSADMIN','BS_COA_MANAGEMENT',8,NULL),
  ('BS_ROLE_SYSADMIN','BS_STOCK_CATEGORY',9,NULL),
  ('BS_ROLE_SYSADMIN','BS_ITEM_MANAGEMENT',10,NULL),
  ('BS_ROLE_SYSADMIN','BS_QUICK_ORDER_ITEMS',11,NULL),
  ('BS_ROLE_SYSADMIN','BS_JOB_REQUEST_ITEM',12,NULL),
  ('BS_ROLE_SYSADMIN','BS_MEDIA',13,NULL),
  ('BS_ROLE_SYSADMIN','BS_PART_BOOK',14,NULL),
  ('BS_ROLE_SYSADMIN','BS_MENU_MANAGEMENT',15,NULL),
  ('BS_ROLE_SYSADMIN','BS_WHATSAPP_DEVICE',16,NULL),
  ('BS_ROLE_SYSADMIN','BS_SYSTEM_LOGS',17,NULL),
  ('BS_ROLE_SYSADMIN','BS_CACHE_CONTROL',18,NULL),
  ('BS_ROLE_SYSADMIN','BS_REQUISITION_ADMIN',19,NULL),
  ('BS_ROLE_SYSADMIN','BS_JOB_REQUEST_ADMIN',20,NULL),
  ('BS_ROLE_SYSADMIN','BS_JOB_REQUEST_PRUNE',21,NULL),
  ('BS_ROLE_SYSADMIN','BS_SETTINGS',22,NULL),
  ('BS_ROLE_SYSADMIN','BS_JOB_REQUEST',23,true),
  ('BS_ROLE_SYSADMIN','BS_QUICK_ORDER',24,true),
  ('BS_ROLE_SYSADMIN','BS_REPAIR_JOB_REQUEST',25,NULL),
  ('BS_ROLE_SYSADMIN','BS_OUTSTANDING_SERVICE_ATTENDANCE',26,NULL),
  ('BS_ROLE_SYSADMIN','BS_REPAIR_SERVICE_ORDERS',27,NULL),
  ('BS_ROLE_SYSADMIN','BS_MOBILIZATION',28,NULL),
  ('BS_ROLE_SYSADMIN','BS_ATTENDANCE_TRIP',29,NULL),
  ('BS_ROLE_SYSADMIN','BS_TECHNICIAN_CALENDAR',30,NULL),
  ('BS_ROLE_SYSADMIN','BS_SERVICE_REPORT',31,NULL),
  ('BS_ROLE_SYSADMIN','BS_SERVICE_HISTORY',32,NULL),
  -- SYSADMIN2
  ('BS_ROLE_SYSADMIN2','BS_USER_MANAGEMENT',1,NULL),
  ('BS_ROLE_SYSADMIN2','BS_DELEGATE_APPROVER',2,NULL),
  ('BS_ROLE_SYSADMIN2','BS_VESSEL_MANAGEMENT',3,NULL),
  ('BS_ROLE_SYSADMIN2','BS_SYSTEM_LOGS',4,NULL),
  -- REQUESTER
  ('BS_ROLE_REQUESTER','BS_ITEM_REQUEST',1,NULL),
  ('BS_ROLE_REQUESTER','BS_QUICK_ORDER',2,true),
  ('BS_ROLE_REQUESTER','BS_USAGE',3,NULL),
  ('BS_ROLE_REQUESTER','BS_JOB_REQUEST',4,true),
  ('BS_ROLE_REQUESTER','BS_BUNKER_REQUEST',5,NULL),
  ('BS_ROLE_REQUESTER','BS_SHIPMENT_REQUEST',6,NULL),
  ('BS_ROLE_REQUESTER','BS_TRACK_ITEM',7,NULL),
  ('BS_ROLE_REQUESTER','BS_FEEDBACK',8,NULL),
  ('BS_ROLE_REQUESTER','BS_PART_BOOK',9,NULL),
  -- ADMIN_TESTING
  ('BS_ROLE_ADMIN_TESTING','BS_ITEM_REQUEST',1,NULL),
  ('BS_ROLE_ADMIN_TESTING','BS_QUICK_ORDER',2,true),
  ('BS_ROLE_ADMIN_TESTING','BS_USAGE',3,true),
  ('BS_ROLE_ADMIN_TESTING','BS_JOB_REQUEST',4,true),
  ('BS_ROLE_ADMIN_TESTING','BS_TRACK_ITEM',5,NULL),
  ('BS_ROLE_ADMIN_TESTING','BS_FEEDBACK',6,NULL),
  ('BS_ROLE_ADMIN_TESTING','BS_PART_BOOK',7,NULL),
  -- REQUESTER_ONLINE
  ('BS_ROLE_REQUESTER_ONLINE','BS_ITEM_REQUEST',1,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_QUICK_ORDER',2,true),
  ('BS_ROLE_REQUESTER_ONLINE','BS_USAGE',3,true),
  ('BS_ROLE_REQUESTER_ONLINE','BS_JOB_REQUEST',4,true),
  ('BS_ROLE_REQUESTER_ONLINE','BS_TRACK_ITEM',5,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_FEEDBACK',6,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_REPAIR_JOB_REQUEST',7,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_SERVICE_REPORT',8,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_SERVICE_HISTORY',9,NULL),
  ('BS_ROLE_REQUESTER_ONLINE','BS_PART_BOOK',10,NULL),
  -- ADMIN
  ('BS_ROLE_ADMIN','BS_ITEM_REQUEST',1,NULL),
  ('BS_ROLE_ADMIN','BS_QUICK_ORDER',2,true),
  ('BS_ROLE_ADMIN','BS_APPROVALS',3,NULL),
  ('BS_ROLE_ADMIN','BS_TRACK_ITEM',4,NULL),
  ('BS_ROLE_ADMIN','BS_FEEDBACK',5,NULL),
  ('BS_ROLE_ADMIN','BS_REPAIR_JOB_REQUEST',6,NULL),
  ('BS_ROLE_ADMIN','BS_REPAIR_SERVICE_ORDERS',7,NULL),
  ('BS_ROLE_ADMIN','BS_SERVICE_REPORT',8,NULL),
  ('BS_ROLE_ADMIN','BS_SERVICE_HISTORY',9,NULL),
  ('BS_ROLE_ADMIN','BS_PART_BOOK',10,NULL),
  -- APPROVER
  ('BS_ROLE_APPROVER','BS_APPROVALS',1,NULL),
  ('BS_ROLE_APPROVER','BS_TRACK_ITEM',2,NULL),
  ('BS_ROLE_APPROVER','BS_REPAIR_SERVICE_ORDERS',3,NULL),
  ('BS_ROLE_APPROVER','BS_PART_BOOK',4,NULL),
  -- REPAIR_MANAGER
  ('BS_ROLE_REPAIR_MANAGER','BS_OUTSTANDING_SERVICE_ATTENDANCE',1,NULL),
  ('BS_ROLE_REPAIR_MANAGER','BS_ATTENDANCE_TRIP',2,NULL),
  ('BS_ROLE_REPAIR_MANAGER','BS_TECHNICIAN_CALENDAR',3,NULL),
  ('BS_ROLE_REPAIR_MANAGER','BS_SERVICE_REPORT',4,NULL),
  ('BS_ROLE_REPAIR_MANAGER','BS_SERVICE_HISTORY',5,NULL),
  -- REPAIR_COORDINATOR
  ('BS_ROLE_REPAIR_COORDINATOR','BS_OUTSTANDING_SERVICE_ATTENDANCE',1,NULL),
  ('BS_ROLE_REPAIR_COORDINATOR','BS_ATTENDANCE_TRIP',2,NULL),
  ('BS_ROLE_REPAIR_COORDINATOR','BS_MY_SERVICE_REPORT',3,NULL),
  ('BS_ROLE_REPAIR_COORDINATOR','BS_SERVICE_HISTORY',4,NULL),
  -- REPAIR_ADMINISTRATOR
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_REPAIR_JOB_REQUEST',1,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_OUTSTANDING_SERVICE_ATTENDANCE',2,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_REPAIR_SERVICE_ORDERS',3,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_MOBILIZATION',4,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_ATTENDANCE_TRIP',5,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_TECHNICIAN_CALENDAR',6,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_SERVICE_REPORT',7,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_SERVICE_HISTORY',8,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_USER_MANAGEMENT',9,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_APPROVAL_RULES',10,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_DELEGATE_APPROVER',11,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_RESEND_APPROVAL',12,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_DOCUMENT_NUMBERING',13,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_VESSEL_MANAGEMENT',14,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_COA_MANAGEMENT',15,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_STOCK_CATEGORY',16,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_ITEM_MANAGEMENT',17,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_JOB_REQUEST_ITEM',18,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_MEDIA',19,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_PART_BOOK',20,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_WHATSAPP_DEVICE',21,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_SYSTEM_LOGS',22,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_CACHE_CONTROL',23,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_REQUISITION_ADMIN',24,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_JOB_REQUEST_ADMIN',25,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_JOB_REQUEST_PRUNE',26,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_SETTINGS',27,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_JOB_REQUEST',28,NULL),
  ('BS_ROLE_REPAIR_ADMINISTRATOR','BS_QUICK_ORDER',29,NULL),
  -- TECHNICIAN
  ('BS_ROLE_TECHNICIAN','BS_OUTSTANDING_SERVICE_ATTENDANCE',1,NULL),
  ('BS_ROLE_TECHNICIAN','BS_ATTENDANCE_TRIP',2,NULL),
  ('BS_ROLE_TECHNICIAN','BS_MY_SERVICE_REPORT',3,NULL),
  ('BS_ROLE_TECHNICIAN','BS_SERVICE_HISTORY',4,NULL),
  -- TECHNICIAN_ADMIN
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_REPAIR_JOB_REQUEST',1,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_OUTSTANDING_SERVICE_ATTENDANCE',2,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_MOBILIZATION',3,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_ATTENDANCE_TRIP',4,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_TECHNICIAN_CALENDAR',5,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_MY_SERVICE_REPORT',6,NULL),
  ('BS_ROLE_TECHNICIAN_ADMIN','BS_SERVICE_HISTORY',7,NULL),
  -- MOBILIZATION_SUPPORT
  ('BS_ROLE_MOBILIZATION_SUPPORT','BS_OUTSTANDING_SERVICE_ATTENDANCE',1,NULL),
  ('BS_ROLE_MOBILIZATION_SUPPORT','BS_MOBILIZATION',2,NULL),
  ('BS_ROLE_MOBILIZATION_SUPPORT','BS_ATTENDANCE_TRIP',3,NULL),
  ('BS_ROLE_MOBILIZATION_SUPPORT','BS_SERVICE_HISTORY',4,NULL),
  -- ACCOUNTING
  ('BS_ROLE_ACCOUNTING','BS_COA_MANAGEMENT',1,NULL),
  -- OS
  ('BS_ROLE_OS','BS_REPAIR_SERVICE_ORDERS',1,NULL),
  ('BS_ROLE_OS','BS_REPAIR_JOB_REQUEST',2,NULL),
  ('BS_ROLE_OS','BS_SERVICE_REPORT',3,NULL),
  ('BS_ROLE_OS','BS_SERVICE_HISTORY',4,NULL),
  -- VESSEL
  ('BS_ROLE_VESSEL','BS_REPAIR_JOB_REQUEST',1,NULL),
  ('BS_ROLE_VESSEL','BS_SERVICE_REPORT',2,NULL),
  ('BS_ROLE_VESSEL','BS_SERVICE_HISTORY',3,NULL),
  -- CREW
  ('BS_ROLE_CREW','BS_ITEM_REQUEST',1,NULL),
  ('BS_ROLE_CREW','BS_QUICK_ORDER',2,true),
  ('BS_ROLE_CREW','BS_TRACK_ITEM',3,NULL),
  ('BS_ROLE_CREW','BS_FEEDBACK',4,NULL),
  ('BS_ROLE_CREW','BS_PART_BOOK',5,NULL),
  -- IT_SUPPORT
  ('BS_ROLE_IT_SUPPORT','BS_WHATSAPP_DEVICE',1,NULL)
) AS v(tmpl, code, sort, soon)
JOIN "Menu" m ON m."MenuCode" = v.code
WHERE NOT EXISTS (
  SELECT 1 FROM "LaunchPointTemplate" lpt
  WHERE lpt."TemplateName" = v.tmpl AND lpt."MenuID" = m."ID"
);

-- 4) Backfill every EXISTING user from their role's template, so nobody's
--    sidebar changes the moment SideNavBar switches over to reading this.
INSERT INTO "LaunchPoint" ("UserName","MenuID","MenuCode","MenuName","Category","SortOrder","IsActive","IsComingSoon","TemplateName")
SELECT u."Username", m."ID", m."MenuCode", m."MenuName", m."Category", lpt."SortOrder", true, lpt."IsComingSoon", lpt."TemplateName"
FROM "User" u
JOIN "LaunchPointTemplate" lpt ON lpt."TemplateName" = 'BS_ROLE_' || upper(u."Role")
JOIN "Menu" m ON m."ID" = lpt."MenuID"
WHERE NOT EXISTS (
  SELECT 1 FROM "LaunchPoint" lp2 WHERE lp2."UserName" = u."Username" AND lp2."MenuID" = m."ID"
);

COMMIT;
