-- ============================================================================
-- Audit trail untuk RequisitionFormTemplate — mencatat setiap perubahan
-- (Create/Update/Publish/Unpublish/Activate/Deactivate/NewVersion/Delete)
-- lewat RequisitionDynamicFormController.
--
-- TemplateID nullable + ON DELETE SET NULL (bukan CASCADE): kalau template
-- draft-nya dihapus, baris audit "Delete" untuk template itu HARUS tetap ada
-- (itu justru baris yang paling penting) — Code/Version didenormalisasi biar
-- tetap bisa ditelusuri walau TemplateID sudah NULL.
--
-- Idempoten. PostgreSQL. Run: staging dulu, verifikasi, baru production.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "RequisitionFormTemplateAudit" (
    "ID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TemplateID" integer NULL REFERENCES "RequisitionFormTemplate"("ID") ON DELETE SET NULL,
    "Code"       varchar(100) NOT NULL,
    "Version"    integer      NOT NULL,
    "Action"     varchar(30)  NOT NULL,  -- Create|Update|Publish|Unpublish|Activate|Deactivate|NewVersion|Delete
    "OldValue"   jsonb        NULL,
    "NewValue"   jsonb        NULL,
    "Remarks"    text         NULL,
    "CreatedBy"  varchar(100) NULL,
    "CreatedAt"  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_reqformtplaudit_template" ON "RequisitionFormTemplateAudit" ("TemplateID");
CREATE INDEX IF NOT EXISTS "idx_reqformtplaudit_code"     ON "RequisitionFormTemplateAudit" ("Code", "CreatedAt");

COMMIT;

-- Verifikasi:
-- SELECT * FROM "RequisitionFormTemplateAudit" ORDER BY "CreatedAt" DESC LIMIT 20;
